# Generated by Django 2.2.4 on 2026-05-31 10:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(default='恒达科技有限公司', max_length=100, verbose_name='公司名称')),
                ('english_name', models.CharField(default='HengDa Science and Technology', max_length=120, verbose_name='英文名称')),
                ('business_one', models.CharField(default='111-111111', max_length=40, verbose_name='业务咨询一')),
                ('business_two', models.CharField(default='222-222222', max_length=40, verbose_name='业务咨询二')),
                ('phone', models.CharField(default='0111-1111111', max_length=40, verbose_name='咨询电话')),
                ('fax', models.CharField(default='0222-2222222', max_length=40, verbose_name='企业传真')),
                ('address', models.CharField(default='某某路某某大道某某号', max_length=200, verbose_name='地址')),
                ('postcode', models.CharField(default='2222-222222', max_length=20, verbose_name='邮编')),
                ('website', models.URLField(default='http://python3web.com', verbose_name='网址')),
                ('map_lng', models.DecimalField(decimal_places=6, default=121.506377, max_digits=10, verbose_name='地图经度')),
                ('map_lat', models.DecimalField(decimal_places=6, default=31.245105, max_digits=10, verbose_name='地图纬度')),
                ('marker_lng', models.DecimalField(decimal_places=6, default=121.507015, max_digits=10, verbose_name='标注经度')),
                ('marker_lat', models.DecimalField(decimal_places=6, default=31.243978, max_digits=10, verbose_name='标注纬度')),
                ('map_content', models.CharField(default='python web企业门户网站开发实战', max_length=200, verbose_name='地图标注说明')),
            ],
            options={
                'verbose_name': '欢迎咨询信息',
                'verbose_name_plural': '欢迎咨询信息',
            },
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='岗位名称')),
                ('description', models.TextField(verbose_name='岗位说明')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否显示')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '招聘岗位',
                'verbose_name_plural': '招聘岗位',
                'ordering': ('ordering', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('personID', models.CharField(max_length=30, verbose_name='身份证号')),
                ('sex', models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=5, verbose_name='性别')),
                ('birth', models.DateField(verbose_name='出生日期')),
                ('email', models.EmailField(max_length=50, verbose_name='邮箱')),
                ('edu', models.CharField(choices=[('大专', '大专'), ('本科', '本科'), ('硕士', '硕士'), ('博士', '博士'), ('其它', '其它')], default='本科', max_length=5, verbose_name='学历')),
                ('school', models.CharField(max_length=40, verbose_name='毕业学校')),
                ('major', models.CharField(max_length=40, verbose_name='专业')),
                ('position', models.CharField(max_length=40, verbose_name='申请职位')),
                ('photo', models.ImageField(upload_to='Resume/', verbose_name='证件照片')),
                ('experience', models.TextField(blank=True, verbose_name='学习或工作经历')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
            ],
            options={
                'verbose_name': '个人简历',
                'verbose_name_plural': '个人简历',
                'ordering': ('-created',),
            },
        ),
    ]
